version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
    
    container_name: tcg-mongo

    env_file: .env

  tcg-tracker:
    build:
      context: .

    image: tcg-tracker:latest
    container_name: tcg-tracker

    ports:
      - "8080:8080"

    env_file: .env

volumes:
  data: