version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
    
    container_name: tcg-mongo

  tcg-tracker:
    build:
      context: .

    ports:
      - "8080:8080"

volumes:
  data:

# docker compose --profile=X up --build
# docker compose --profile=X down