version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
    
    container_name: tcg-mongo

  tcg-tracker:
    build:
      context: .
      dockerfile: Dockerfile.dev

    image: tcg-tracker:latest
    container_name: tcg-tracker

    ports:
      - "8080:8080"

    environment:
      NODE_ENV: ${ENVIRON}

    depends_on:
      - tcg-mongo

volumes:
  data:

# docker compose --profile=dev up -d --build