version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
    
    container_name: tcg-mongo

  tcg-tracker:
    build:
      context: .

    container_name: tcg-tracker
    image: tcg-tracker:latest

    ports:
      - "8080:8080"

    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
      - MONGO_HOSTNAME=host.docker.internal
      - MONGO_PORT=27017

    stdin_open: true
    tty: true

    depends_on:
      - tcg-mongo

volumes:
  data:

# docker compose up -d --build
# docker attach tcg-tracker