version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
    
    container_name: tcg-mongo

    env_file: .env

    profiles:
      - dev

  # tcg-tracker-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev

  #   image: tcg-tracker:latest
  #   container_name: tcg-tracker

  #   ports:
  #     - "8080:8080"

  #   depends_on: tcg-mongo

  #   profiles:
  #     - dev

  tcg-tracker:
    build:
      context: .

    image: tcg-tracker:latest
    container_name: tcg-tracker

    ports:
      - "8080:8080"

    env_file: .env

    profiles:
      - prod

volumes:
  data:

# docker compose --profile=X up --build
# docker compose --profile=X down