version: "3.8"

services:
  tcg-mongo:
    image: mongo:6

    ports: 
      - "27017:27017"

    volumes:
      - data:/data/db
  
    env_file:
      - ${ENVIRON}.env
    
    container_name: tcg-mongo

    profiles:
      - dev

  tcg-tracker:
    build:
      context: .

    image: tcg-tracker:latest
    container_name: tcg-tracker

    ports:
      - "8080:8080"

    env_file:
      - ${ENVIRON}.env

    stdin_open: true
    tty: true

volumes:
  data:

# docker compose --profile=dev up -d --build
# docker attach tcg-tracker